config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :cocktails do
    resources :doses, only: [ :new, :create, :destroy, :edit ]
  end
  resources :ingredients, only: [ :show ]
  # resources :doses, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :ingredient, scope: :cocktail
  # validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:create]
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
      render :new # how to pass the rake??S??AD?D/a/fG?A?
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])

  end
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    # how to actually match the coktail id??
    @ingredient = Ingredient.find(params[:id])
    # @doses = Dose.where(ingredient_id: @ingredient.id)
    # @cocktails = doses.map(&:cocktail).uniq!
    @cocktails = @ingredient.cocktails

    # @cocktail = Cocktail.find(params[:cocktail_id])
    # @ingredient.cocktail_id = @cocktail.id
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Add a Cocktail", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<%= render 'form' %>
<div class="text-center">
  <%= link_to "Back", cocktails_path %>

</div>

app/views/cocktails/index.html.erb
<div class="wrapper-grey">
  <div class="container text-center">
    <div class="row">
    <h1>Don't judge pls</h1>
    <% @cocktails.each do |cock| %>
      <div class="col-xs-12 col-sm-4 col-l-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path((cock.photo || 'default.png'), height: 300, width: 400, crop: :fill)%>')">

          <div class="card-description">
            <h3><%= cock.name %></h3>
          </div>
          <div class="card-link form-inline">
            <p><%= link_to 'Show Details', cocktail_path(cock) %></p>
            <p><%= link_to 'Edit', edit_cocktail_path(cock) %></p>
            <p><%= link_to 'Delete', cocktail_path(cock), method: :delete, data: { confirm: "Are you sure?" } %></p>
          </div>
          <a class="card-link" href="#" ></a>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>


<div class="create text-center">
  <%= link_to 'Create a new Cocktail', new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="container text-center">
  <h1>Your selected Cocktail</h1>
  <h2><%= @cocktail.name %></h2>
  <div class="ingred">
    <h2>Ingredients: </h2>
    <% @cocktail.doses.each do |dose| %>
      <p><%= dose.description %> <%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %></p>
      <%= link_to "Delete", cocktail_dose_path(dose), class: "label label-warning", method: :delete %>
    <% end %>
  </div>
</div>
<%= render template: 'doses/_form.html.erb' %>
<div class="text-center">
  <%= link_to "Back", cocktails_path %>
  <%= link_to "Edit", edit_cocktail_path %>
</div>

<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

app/views/doses/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient, include_blank:"Select an ingredient" %>
        <%= f.submit "Add an ingredient", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<%= render 'form' %>

app/views/ingredients/show.html.erb
<div class="container text-center">
  <h1>All cocktails with <%= @ingredient.name %></h1>
  <ul>
    <% @cocktails.each do |cock| %>
      <li> <%= link_to cock.name, cocktail_path(cock) %> </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://fonts.googleapis.css?family=Open+Sans:400,300,700|Raleway:300,400,500,700">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,188,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://media.timeout.com/images/103279372/image.jpg');">
  <div class="banner-content">
    <h1>Chestnut's Tails</h1>
    <p>Busy night...but there's always room for another!</p>
    <%= link_to "GET IN", cocktails_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<!--

<%= cl_image_tag("qlfk78dpanatk39i5qf1",
      width: 400, height: 300, crop: :fit) %>
 -->

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<div id="footer-black">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-instagram"></i></a></li>
          <li><a href="#"><i class="fa fa-youtube"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <p>This is a Cocktail Website @ LeWagon</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- NAVBAR -->